// M5 summary — autogenerated
(function(){
  window.MODULE_SUMMARIES = window.MODULE_SUMMARIES || {};
  window.MODULE_SUMMARIES.M5 = {
  "title": "Modul 5 — Cybercrime & Keamanan Sistem Informasi",
  "sections": [
    {
      "h": "Cybercrime: definisi & karakteristik",
      "items": [
        "Cybercrime = kejahatan yang memanfaatkan komputer/jaringan sebagai alat, target, atau tempat terjadinya kejahatan.",
        "Ciri: lintas batas, mudah disamarkan, cepat menyebar, dan berdampak luas (data, finansial, reputasi)."
      ]
    },
    {
      "h": "Contoh bentuk serangan yang sering dibahas",
      "items": [
        "Malware (virus/worm/trojan), phishing/social engineering, hacking & eksploitasi celah, deface, DoS/DDoS, dan pencurian akun/data.",
        "Sasaran umum: kerahasiaan (confidentiality), integritas (integrity), dan ketersediaan (availability) — CIA triad."
      ]
    },
    {
      "h": "Pencegahan & respons (cara ingat cepat)",
      "items": [
        "Prevent: patch/update, hardening, least privilege, backup, MFA, dan edukasi pengguna.",
        "Detect: logging, monitoring, IDS/IPS, audit berkala.",
        "Respond/Recover: isolasi insiden, forensik, pemulihan dari backup, perbaikan celah, dan pelaporan sesuai SOP/hukum."
      ]
    }
  ]
};
})();
