// M2 summary — autogenerated
(function(){
  window.MODULE_SUMMARIES = window.MODULE_SUMMARIES || {};
  window.MODULE_SUMMARIES.M2 = {
  "title": "Modul 2 — Sejarah TI & Kode Etik Profesi TI",
  "sections": [
    {
      "h": "Garis besar sejarah TI (timeline)",
      "items": [
        "TI berkembang dari kebutuhan manusia menyimpan/menyebarkan informasi: simbol–tulisan–media cetak–telekomunikasi–komputer–internet.",
        "Periode kunci: prasejarah (gambar/tulisan), Mesir (papirus), Gutenberg (mesin cetak), komputer awal (mis. ENIAC), hingga era internet & jaringan.",
        "Dampak utama: percepatan komunikasi, lahirnya ekonomi digital (e-commerce, e-business, e-government, dll)."
      ]
    },
    {
      "h": "Etika profesi: prinsip umum",
      "items": [
        "Etika profesi adalah pedoman perilaku anggota profesi agar bekerja benar dan tidak merugikan pihak lain.",
        "Prinsip umum yang ditekankan: tanggung jawab, keadilan, objektivitas/kejujuran, integritas moral, dan menghormati hak orang lain.",
        "Etika profesi menjaga kepercayaan publik serta kualitas layanan/proyek TI."
      ]
    },
    {
      "h": "Kode etik profesi TI (apa yang dilarang/diwajibkan)",
      "items": [
        "Kode etik mengatur: hubungan dengan klien/atasan/masyarakat, penggunaan aset & data, serta keamanan sistem.",
        "Larang keras: menyebarkan malware, mencuri/menyalahgunakan data, membuat backdoor, plagiarisme/menjiplak, dan menutup-nutupi celah demi keuntungan pribadi.",
        "Intinya: buat sistem yang aman & bermanfaat, transparan soal risiko, dan patuhi hukum/kontrak."
      ]
    }
  ]
};
})();
