// M4 summary — autogenerated
(function(){
  window.MODULE_SUMMARIES = window.MODULE_SUMMARIES || {};
  window.MODULE_SUMMARIES.M4 = {
  "title": "Modul 4 — Aspek Hukum TI: HAKI, UU, dan Etika Legal",
  "sections": [
    {
      "h": "Kenapa aspek hukum penting di TI",
      "items": [
        "Aktivitas TI menyangkut data, transaksi, karya digital, dan layanan publik—semuanya punya konsekuensi hukum.",
        "Profesional TI wajib paham batasan legal: privasi, keamanan, hak cipta, dan bukti elektronik."
      ]
    },
    {
      "h": "HAKI yang sering muncul",
      "items": [
        "Hak Cipta: melindungi karya (termasuk software sebagai karya cipta).",
        "Paten: melindungi invensi/temuan; biasanya terkait metode/alat (bergantung yurisdiksi).",
        "Merek/Desain Industri/Rahasia Dagang: melindungi identitas bisnis, tampilan produk, dan informasi rahasia bernilai ekonomi.",
        "Lisensi software: menentukan hak pakai, distribusi, modifikasi (proprietary vs open source)."
      ]
    },
    {
      "h": "UU/aturan TI (umum) & bukti elektronik",
      "items": [
        "Transaksi elektronik membutuhkan aturan: autentikasi, integritas data, dan non-repudiation (mis. tanda tangan elektronik).",
        "Dokumen/bukti elektronik bisa sah jika memenuhi ketentuan hukum (integritas, dapat diakses/ditampilkan, dsb).",
        "Pelanggaran umum: akses tanpa izin, penyadapan, manipulasi data, penipuan online, dan pelanggaran hak cipta."
      ]
    }
  ]
};
})();
