// M3 summary — autogenerated
(function(){
  window.MODULE_SUMMARIES = window.MODULE_SUMMARIES || {};
  window.MODULE_SUMMARIES.M3 = {
  "title": "Modul 3 — Organisasi Profesional & Profesi di Bidang TI",
  "sections": [
    {
      "h": "Kenapa organisasi profesi penting",
      "items": [
        "Menetapkan standar kompetensi & etika, meningkatkan kualitas anggota, dan melindungi masyarakat/klien.",
        "Menjadi wadah jejaring, pelatihan, sertifikasi, konferensi, serta advokasi profesi TI."
      ]
    },
    {
      "h": "Contoh organisasi profesi (internasional & Indonesia)",
      "items": [
        "Internasional: ACM, IEEE, dan SEARCC (regional).",
        "Indonesia: APTIKOM, IPKIN, APJII, IAI (contoh organisasi terkait TI/informatika).",
        "Peran umumnya: standardisasi, pengembangan kompetensi, serta kolaborasi industri–akademik."
      ]
    },
    {
      "h": "Gambaran profesi TI & standardisasi",
      "items": [
        "Kelompok peran: software (software engineer/programmer/web), hardware/network, operasional sistem, data (DBA), dan keamanan informasi.",
        "Standardisasi profesi mendorong mutu kerja, pembagian peran yang jelas, serta jalur karier/sertifikasi.",
        "Prinsip kompetensi kerja yang sering dirujuk: level mandiri–terbimbing–supervised, dll (sesuai konteks standardisasi)."
      ]
    },
    {
      "h": "Pekerjaan TI yang sering dibahas",
      "items": [
        "Software engineer/developer: rancang–bangun–uji–rawat aplikasi.",
        "DBA: kelola database (keamanan, performa, backup, integritas data).",
        "Network architect/engineer: desain & operasi jaringan + keamanan.",
        "Web developer/admin & information security analyst: bangun/kelola layanan web dan jaga keamanan informasi."
      ]
    }
  ]
};
})();
