// M1 summary — autogenerated
(function(){
  window.MODULE_SUMMARIES = window.MODULE_SUMMARIES || {};
  window.MODULE_SUMMARIES.M1 = {
  "title": "Modul 1 — Prinsip Dasar Etika, Profesi, dan Profesionalisme TI",
  "sections": [
    {
      "h": "Etika: inti yang harus diingat",
      "items": [
        "Etika = ukuran baik–buruk tindakan; dipakai sebagai pedoman saat memilih tindakan dan menilai perilaku.",
        "Etika umum vs etika khusus: etika khusus mencakup etika individu & etika sosial (kewajiban terhadap diri dan orang lain).",
        "Ciri etika: bersifat normatif (patokan), terkait perbuatan manusia, dan memberi dasar pertanggungjawaban moral."
      ]
    },
    {
      "h": "Jenis, manfaat, dan prinsip etika",
      "items": [
        "Jenis etika: filosofis/teoritis, teologis (agama), sosiologis (masyarakat), deskriptif (apa adanya), normatif (apa seharusnya), deontologis (kewajiban), teleologis (tujuan/hasil).",
        "Manfaat etika: menuntun keputusan, mencegah konflik/kerugian, membangun kepercayaan, dan membantu menyelesaikan masalah.",
        "Prinsip etika yang sering muncul: kebaikan, persamaan (anti-diskriminasi), keadilan, kebebasan (hak memilih), dan kebenaran."
      ]
    },
    {
      "h": "Profesi & profesionalisme",
      "items": [
        "Profesi = pekerjaan berbasis keahlian/pengetahuan khusus, ada standar, tanggung jawab, dan diakui masyarakat; tidak semua pekerjaan = profesi.",
        "Ciri/syarat profesi: pendidikan/latihan khusus, kode etik, organisasi profesi, sertifikasi/lisensi, layanan publik, dan otonomi profesi.",
        "Profesionalisme = cara bekerja sesuai standar: kompeten (skill+knowledge), berintegritas, komunikatif, disiplin, dan bertanggung jawab."
      ]
    },
    {
      "h": "Checklist jadi profesional di TI",
      "items": [
        "Bangun 3 pilar: skill (teknis), knowledge (konsep), attitude (etik & kolaborasi).",
        "Biasakan: tepat waktu, rapi, dokumentasi jelas, komunikasi efektif, dan menjaga kerahasiaan data/informasi.",
        "Ambil keputusan berdasar etika: pikir dampak ke pengguna/organisasi, pilih tindakan yang paling adil & dapat dipertanggungjawabkan."
      ]
    }
  ]
};
})();
