// M6 summary — autogenerated
(function(){
  window.MODULE_SUMMARIES = window.MODULE_SUMMARIES || {};
  window.MODULE_SUMMARIES.M6 = {
  "title": "Modul 6 — Pendirian Usaha Berbasis TI & Prosedurnya",
  "sections": [
    {
      "h": "Apa yang dimaksud usaha berbasis TI",
      "items": [
        "Badan usaha = kesatuan yuridis/teknis/ekonomi untuk mencari laba; perusahaan = tempat faktor produksi dikelola (beda konsep).",
        "Usaha TI tidak cuma komputer: mencakup perangkat, proses, dan pengolahan informasi (data/suara/video) untuk bisnis.",
        "Contoh bidang usaha TI: software house, konsultan implementasi TI (hardware/software), distributor produk TI, training/pendidikan TI."
      ]
    },
    {
      "h": "Kewirausahaan (entrepreneurship) — kata kunci",
      "items": [
        "Wirausaha = membangun & mengelola bisnis untuk untung dengan mengambil risiko; menekankan kreativitas & inovasi.",
        "Entrepreneur dipandang sebagai pihak yang menanggung risiko/ketidakpastian dalam sistem ekonomi (Cantillon).",
        "Benang merah definisi para pakar: menangkap peluang, menciptakan nilai baru, mengorganisasi sumber daya, dan berani mengambil risiko."
      ]
    },
    {
      "h": "Startup TI (ringkas)",
      "items": [
        "Startup = usaha rintisan (biasanya berbasis teknologi) yang mencari model bisnis yang scalable dan repeatable.",
        "Fokus awal: problem–solution fit → product–market fit → scaling (tim, proses, pendanaan, dan operasional).",
        "Validasi cepat: riset pasar, MVP, iterasi berbasis feedback, dan metrik (user growth, retention, revenue)."
      ]
    }
  ]
};
})();
